config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'toppage#index'

  get '/about_Next innovation', to: 'toppage#about'

  resources :users, only: [:index, :show] do
    member do
      get :goods
    end
  end

  resources :profiles, only: [:new, :create, :edit, :update]

  resources :results, except: [:index] do
    resource :goods, only: [:create, :destroy]
  end

  resources :comments, only: [:create, :destroy]

  get '/good_ranking', to: 'goods#index'

  resources :notifications, only: [:index]
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  comment    :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  result_id  :bigint
#  user_id    :bigint
#
# Indexes
#
#  index_comments_on_result_id  (result_id)
#  index_comments_on_user_id    (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (result_id => results.id)
#  fk_rails_...  (user_id => users.id)
#
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :result

  validates :comment, presence: true, length: { maximum: 255 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:destroy]

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.result_id = params[:result_id]
    @result = Result.find(params[:result_id])
    @comments = Comment.where(result_id: @result.id)

    # 自分がコメントした時は通知しないように変更する
    unless @result.user == current_user
      Notification.create(user_id: current_user.id, result_id: @result.id, kind: 'comment')
    end

    @comment_save = @comment.save

  end

  def destroy
    @result = Result.find(@comment.result_id)
    @comments = Comment.where(result_id: @result.id)
    @comment.destroy

  end

  private
  def comment_params
    params.require(:comment).permit(:comment)
  end

  def correct_user
    @comment = current_user.comments.find_by(id: params[:id])
    if current_user.admin?
      @comment = Comment.find(params[:id])
    elsif @comment == nil
      redirect_to root_url
    end
  end
end

app/views/comments/_comments.html.erb
<div class="margin-bottom10"><i class="far fa-comment"></i> <%= comments.count %> 件のコメント</div>


<% comments.each do |comment| %>
  <% if comment.user == result.user %>
    <i class="fas fa-user"></i>
  <% end %>
  <%= link_to comment.user.name, user_path(comment.user) %>
  <span class="pull-right text-muted margin-right10"><%= comment.created_at.strftime('%Y/%m/%d') %></span>
  <% if comment.user == current_user%>
    <span class="pull-right margin-right10">
      <%= link_to comment_path(comment), method: :delete, class: 'text-danger', data: { confirm: '本当に削除しますか？'}, remote: true do %>
        <i class="fas fa-trash-alt"></i>
      <% end %>
    </span>
  <% end %>
  <% if user_signed_in? == false %>
  <% elsif current_user.admin? %>
    <%= link_to '不正なコメント', comment_path(comment), method: :delete, class: 'btn btn-danger btn-xs', data: { confirm: '管理者権限でこのコメントを削除しますか？'}, remote: true %>
  <% end %>
  <div class="box margin-bottom10"><%= simple_format(comment.comment) %></div>
<% end %>

app/views/comments/create.js.erb
<% if @comment_save %>
  $('#comment_field').val('');
  $('#comment').html("<%= j(render 'comments/comments', comments: @comments, result: @result) %>");
  $('#error').removeClass('alert alert-warning').empty();
<% else %>
  $('#error').addClass('alert alert-warning').text("文字数がオーバーしています");
<% end %>

app/views/comments/destroy.js.erb
$('#comment').html("<%= j(render 'comments/comments', comments: @comments, result: @result) %>");