config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'toppage#index'

  get '/about_Next innovation', to: 'toppage#about'

  resources :users, only: [:index, :show] do
    member do
      get :goods
    end
  end

  resources :profiles, only: [:new, :create, :edit, :update]

  resources :results, except: [:index] do
    resource :goods, only: [:create, :destroy]
  end

  resources :comments, only: [:create, :destroy]

  get '/good_ranking', to: 'goods#index'

  resources :notifications, only: [:index]
end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id         :bigint           not null, primary key
#  check      :boolean          default(FALSE)
#  kind       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  result_id  :bigint
#  user_id    :bigint
#
# Indexes
#
#  index_notifications_on_result_id  (result_id)
#  index_notifications_on_user_id    (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (result_id => results.id)
#  fk_rails_...  (user_id => users.id)
#
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :result
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    # result_idがcurrent_userの作った作品のidと一緒のものを取り出す
    current_user_notifications = Notification.where(result_id: current_user.results.select(:id)).order('created_at DESC')
    @check_notifications = current_user_notifications.where(check: true).limit(10)

    @uncheck_notifications = current_user_notifications.where(check: false)
  end

  private
  def check_update
    @uncheck_notifications.each do |notification|
      notification.update(check: true)
    end
  end
end

app/helpers/notification_helper.rb
module NotificationHelper
  def uncheck_notifications
    notifications = Notification.where(result_id: current_user.results.select(:id)).order('created_at DESC')
    uncheck_notifications = notifications.where(check: false).count
  end
end

app/views/notifications/_notifications.html.erb
<% notifications.each do |notification| %>
  <div class='eachcontent partition'>
    <% if notification.kind == "good"%>
      <p><i class="fas fa-thumbs-up"></i> いいね <%= time_ago_in_words(notification.created_at) %></p>
      <p>
        <%= link_to notification.user.name, user_path(notification.user) %>さんが
        あなたの作品「<%= link_to notification.result.title, result_path(notification.result) %>」を
        いいねしました
      </p>
    <% else %>
      <p><i class="far fa-comment"></i> コメント <%= time_ago_in_words(notification.created_at) %></p>
      <p>
        <%= link_to notification.user.name, user_path(notification.user) %>さんが
        あなたの作品「<%= link_to notification.result.title, result_path(notification.result) %>」に
        コメントしました
      </p>
    <% end %>
  </div>
<% end %>

app/views/notifications/index.html.erb
<div class="row">
  <div class="col-sm-9 col-sm-push-3">
    <div class="home-content b-bottom margin-bottom10 color"><i class="fas fa-bell color"></i> 通知</div>
      <div class="new-look-bg">
        <%= render 'notifications/notifications', notifications: @uncheck_notifications %>
      </div>
      <%= render 'notifications/notifications', notifications: @check_notifications %>
    </div>

    <%= render 'layouts/home_nav'%>
  </div>
</div>