config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'toppage#index'

  get '/about_Next innovation', to: 'toppage#about'

  resources :users, only: [:index, :show] do
    member do
      get :goods
    end
  end

  resources :profiles, only: [:new, :create, :edit, :update]

  resources :results, except: [:index] do
    resource :goods, only: [:create, :destroy]
  end

  resources :comments, only: [:create, :destroy]

  get '/good_ranking', to: 'goods#index'

  resources :notifications, only: [:index]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  admin                  :boolean          default(FALSE)
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  name                   :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

          validates :name, presence: true, length: { maximum: 20 }

  has_many :profiles, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :goods, dependent: :destroy
  has_many :good_results, through: :goods, source: :result

  has_many :notifications, dependent: :destroy

  def good(result)
    self.goods.find_or_create_by(result_id: result.id)
  end

  def ungood(result)
    good = self.goods.find_by(result_id: result)
    good.destroy if good
  end

  def good?(result)
    self.good_results.include?(result)
  end

  has_many :comments, dependent: :destroy

  # アップデートをcurrent_passwordなし行うためのメソッド
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    user_detail
    @results = @user.results.order('created_at DESC')
  end
  def goods
    user_detail
    @results = @user.good_results
  end

  private

  def user_detail
    @user = User.find(params[:id])
    @profile = Profile.find_by(user_id: @user.id)
  end
end

app/views/users/_user_show.html.erb
<%# ユーザー詳細 %>
<div class="row margin-top20">

  <div class="col-sm-3">
    <div class="panel panel-default">
      <div class="panel-heading partition text-center">
        <span><%= user.name %></span>
      </div>
      <div class="panel-body">
        <%= render 'profiles/profile', profile: @profile %>

      
        <% if user == current_user %>
          <% if @profile %>
            <%= link_to edit_profile_path(current_user), data: {"turbolinks" => false} do %>
              <i class="fas fa-user-edit"></i>プロフィール編集
            <% end %>
          <% else %>
            <a href="/profiles/new" class="pull-right"><i class="fas fa-user-edit"></i>プロフィール編集</a>
          <% end %>
        <% end %>

        <% if user_signed_in? == false %>
        <% elsif current_user.admin? %>
          <%= form_for(user, url:user_registration_path(user),
                        html: { method: :delete }, 
                        data: {confirm: '管理者権限でこのアカウントを削除しますか？'},
                        class: 'btn btn-danger') do |f| %>
            <%= hidden_field_tag :user_id, user.id %>
            <%= f.submit '不正なアカウント', class: 'btn btn-danger margin-top10' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-sm-9">
    <%= link_to user_path(user), style: 'text-decoration: none' do %>
      <span class="btn nomalbtn <%= 'now' if current_page?(user_path(user)) %>">
        作品 <span class="badge"><%= user.results.count %></span>
      </span>
    <% end %>
    
    <%= link_to goods_user_path(user), style: 'text-decoration: none' do %>
      <span class="btn goodbtn <%= 'now' if current_page?(goods_user_path(user)) %>">
        いいねした作品 <span class="badge"><%= user.good_results.count %></span>
      </span>
    <% end %>

    <div class="margin-top10">
      <% if results == [] %>
        <div class="text-muted eachcontent">
          作品はありません
        </div>
      <% end %>

      <%= render 'results/results', results: results %>
    </div>
  </div>
</div>

app/views/users/_users.html.erb
<% users.each do |user| %>
  <div class='eachcontent partition'>
    <p><i class="fas fa-user"></i> <%= link_to user.name, user_path(user) %></p>    

    <% unless user.results == [] %>
      登録した作品 <span class='green'><%= user.results.count %></span> /
    <% end %>
    <span class="margin-right5">いいねした作品 <%= user.good_results.count %></span>
    <%# ユーザーのプロフィールを表示、ツイッターとgithubアカウントを表示したい %>
    <%# eachで取り出しているuserをもとに、Profileテーブルからデータを取り出せるか %>
  </div>
<% end %>

app/views/users/goods.html.erb
<%= render 'users/user_show', user: @user, results: @results, profile: @profile %>

app/views/users/index.html.erb
<%# ユーザー一覧 %>
<div class="row">
  <div class="col-sm-9 col-sm-push-3">
    <div class="home-content users-b-bottom margin-bottom10"><i class="fas fa-users"></i> ユーザー</div>
    <div class="panel-body eachbody">
      <%= render 'users/users', users: @users %>
    </div>
  </div>

  <%= render 'layouts/home_nav'%>
</div>

app/views/users/show.html.erb
<%= render 'users/user_show', user: @user, results: @results, profile: @profile %>