config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'toppage#index'

  get '/about_Next innovation', to: 'toppage#about'

  resources :users, only: [:index, :show] do
    member do
      get :goods
    end
  end

  resources :profiles, only: [:new, :create, :edit, :update]

  resources :results, except: [:index] do
    resource :goods, only: [:create, :destroy]
  end

  resources :comments, only: [:create, :destroy]

  get '/good_ranking', to: 'goods#index'

  resources :notifications, only: [:index]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <% if message_type == 'alert' %>
    <div class="alert alert-danger text-center"><%= message %></div>
  <% elsif message_type == 'notice' %>
    <div class="alart alert-success text-center"><%= message %></div>
  <% else %>
    <div class="alert alert-<%= message_type %> text-center"><%= message %></div>
  <% end %>
<% end %>

app/views/layouts/_home_nav.html.erb
<div class="col-sm-3 col-sm-pull-9  margin-top20">
  <ul class="nav nav-pills nav-stacked text-center">
    <li role="presentation" class="<%= 'active' if current_page?(root_path) %>"><a href="/" ><i class="fas fa-share-square"></i> 最新の作品</a></li>
    <li role="presentation" class="<%= 'active' if current_page?(good_ranking_path) %>"><a href="/good_ranking"><i class="fas fa-crown"></i> いいねランキング</a></li>
    <li role="presentation" class="<%= 'active' if current_page?(users_path) %>"><a href="/users"><i class="fas fa-users"></i> ユーザー</a></li>

    <% if user_signed_in? %>
      <div class="partition margin-top10 margin-bottom10"></div>
    
      <li role="presentation">
        <%= link_to user_path(current_user) do %>
          <i class="fas fa-user"></i> マイページ
        <% end %>
      </li>
      <li role="presentation" class="<%= 'active' if current_page?(notifications_path) %>">
        <a href="/notifications"><i class="fas fa-bell"></i> 通知 <span class="badge">  <%= uncheck_notifications %></span></a>
      </li>
      <% if current_user.profiles != [] %>
        <li>
          <%= link_to edit_profile_path(current_user), data: {"turbolinks" => false} do %>
            <i class="fas fa-user-edit"></i> プロフィール
          <% end %>
        </li>
      <% else %>
        <li><a href="/profiles/new" data-turbolinks="false"><i class="fas fa-user-edit"></i> プロフィール</a></li>
      <% end %>
      <li role="presentation"><a href="/users/edit" ><i class="fas fa-cog"></i> アカウント設定</a></li>

      <div class="partition margin-top10 margin-bottom10"></div>
      <li>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" } %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/_navbar.html.erb
<header>
  <div class="container">
    <a href="/" class='navlogo'>Next innovation</a>
    <span class="dropdown">
      <%# <button class="btn navpull dropdown-toggle" type="button" data-toggle="dropdown"> %>
        <%# <i class="far fa-caret-square-down"></i> %>
      <%# </button> %>
      <ul class="dropdown-menu" role="menu">
        <li><a href='/'><i class="fas fa-share-square"></i> 最新の作品</a></li>
        <li class="divider"></li>
        <li><a href='/good_ranking'><i class="fas fa-crown"></i> いいねランキング</a></li>
        <li class="divider"></li>
        <li><a href='/users'><i class="fas fa-users"></i> ユーザー</a></li>
      </ul>
    </span>

    <% if user_signed_in? %>
      <span class="dropdown pull-right navicon">
        <%# <button class=" btn dropdown-toggle background nav-user" type="button" data-toggle="dropdown">
          <span class="naviconfont"><i class="fas fa-user-circle"></i> <i class="fas fa-caret-down"></i></span>
        </button> %>
        <ul class="dropdown-menu" role="user">
          <li>
            <%= link_to user_path(current_user) do %>
              <i class="fas fa-user"></i> マイページ</a>
            <% end %>
          </li>
          <li class="divider"></li>
          <% if current_user.profiles != [] %>
            <li>
              <%= link_to edit_profile_path(current_user), data: {"turbolinks" => false} do %>
                <i class="fas fa-user-edit"></i>プロフィール
              <% end %>
            </li>
          <% else %>
            <li><a href="/profiles/new" data-turbolinks="false"><i class="fas fa-user-edit"></i>プロフィール</a></li>
          <% end %>
          <li><a href="/users/edit"><i class="fas fa-cog"></i> アカウント設定</a></li>

          <li class="divider"></li>
          <li>
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" } %>
          </li>
        </ul>
      </span>

      <a href="/notifications"><span class="badge pull-right margin-top10 nav-count"><i class="far fa-bell"></i> <%= uncheck_notifications %></span></a>

      <%= link_to new_result_path, class:'white', data: {"turbolinks" => false} do %>
        <span class="btn pull-right result-new margin-top10 margin-right5">
          <i class="fas fa-edit"></i> 作品登録
        </span>
      <% end %>
      
    <% else %>
      <%= link_to new_user_session_path, class: 'white' do %>
        <span class="btn pull-right navfont">
          <span>ログイン</span>
        </span>
      <% end %>
      
      <%= link_to new_user_registration_path, class: 'white' do %>
        <span class="btn pull-right navfont signup">
          アカウント登録
        </span>
      <% end %>
    <% end %>
  </div>
</header>

app/views/layouts/_welcome.html.erb
<% if current_page?(root_path) || current_page?(users_path) || current_page?(good_ranking_path) %>
  <div class="welcome text-center">
    <h1 class="welcometitle">Next innovation<i class="fas fa-share-square "></i></h1>
    <span><h2>今ここにない未来は自分で創る</h2></span>


    <h3>自分で作ったアプリやサイトの共有スペース</h3>
    
    <div class="welcomecontent">
    <h4><i class="fas fa-caret-right"></i> 完璧を目指すよりまず終わらせろ</h4>
    </div>
    
    
    <a class='btn welcomebtn' href="/users/sign_up">アカウント登録</a>
    <a class='btn welcomebtn' href="/users/sign_in">ログイン</a>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width,initial-scale=1">

    <% if @result %>
      <meta name="twitter:card" content="summary">
      <meta name="twitter:title" content="<%= @result.subtitle %>〜<%= @result.title %>〜 - Next innovation">
      <meta name="twitter:description" content="<%= @result.detail %>">
      <meta name="twitter:image" content="https://uploda4.ysklog.net/06937f836c4645a5c7d45ad65648ae14.png" >
    <% else %>
      <meta name="twitter:card" content="summary_large_image">
      <meta name="twitter:title" content="Next innovation~オリジナルアプリやwebサイトの共有スペース~">
      <meta name="twitter:description" content="みんなが作ったオリジナルアプリ、webサイトが見られます！自分の作品を登録すると、色々な人に使ってもらえます。">
      <meta name="twitter:image" content="https://uploda4.ysklog.net/c894477bd936e3fc952b0f9c614a108c.png">
    <% end %>

    <title>Next innovation</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

  </head>

  <body>
  <% unless current_page?(root_path) %>
    <%= render 'layouts/navbar' %>
  <% end %>
    <%= render 'layouts/flash_messages' %>
    <% if user_signed_in? %>
    <%# ログイン中 %>
      <div class="container margin-top10">
        <%= yield %>
      </div>
    <% else %>
    <%# ログイン前 %>
      <%= render 'layouts/welcome'%>
      <div class="container margin-top10">
        <%= yield %>
      </div>
    <% end %>
    <footer>
    </footer>
  </body>
</html>